---
title: "Case study on the EDGAR report on the global greenhouse gas missions"
author: "Chris-Gabriel Islam"
format: pdf
---

# Task description

The European Commission regularly publishes the Emissions Database for Global Atmospheric Research (EDGAR) report on the global greenhouse gas (GHG) emissions around the world. The latest data is published here: https://edgar.jrc.ec.europa.eu/report_2024?vis=ghgpop#data_download\
\
Using data from the above website -- specifically, the data contained in the EDGAR GHG emissions files -- prepare three charts (with the specifications described below) and, alongside each chart, provide a maximum of three bullet points explaining the main data trends.

-   Chart 1 -- Evolution of GHG growth in the euro area, European Union (EU27) and worldwide;

-   Chart 2 -- Comparison of countries\' GHG emissions per capita aggregated according to the World Bank income groups;

-   Chart 3 -- Contribution of individual country and continent GHG emissions to total world GHG emissions.

Moreover, describe the process and tools that you have used for creating your visualisations. Provide your answer in a PDF file format, not exceeding three pages.

# Solution

## Chart 1

## Chart 2

## Chart 3

# Process description

For creating this PDF, I used Quarto, an open-source scientific and technical publishing system. The ETL processes are written in R while the formatting of the report is written in Markdown. To keep the report reproducible, I created a virtual environment using renv and also used Git. The R code is hidden in this reproducible report, but it can be accessed on GitHub.
